### ISSUE TITLE
Does it work with Westend?

### ISSUE THREAD

**Issue by gituser** [figment-networks/polkadothub-indexer#44]
Hello.

Trying to set up indexer with the Polkadot's westend network.

* i've setup up polkadot with `--pruning=archive`
* set up `polkadothub-proxy` it works fine
* now the indexer gives me something like this:
```
{"level":"info","time":"2021-02-18T16:57:20.742+0300","msg":"running indexer task [stage=stage_sequencer] [task=ValidatorSessionSeqCreator] [height=3522026]"}
{"level":"info","time":"2021-02-18T16:57:20.742+0300","msg":"running indexer task [stage=stage_sequencer] [task=ValidatorSeqCreator] [height=3522026]"}
{"level":"info","time":"2021-02-18T16:57:20.746+0300","msg":"running indexer task [stage=stage_parser] [task=RewardEraSeqCreator] [height=3522026]"}
{"level":"info","time":"2021-02-18T16:57:20.747+0300","msg":"running indexer task [stage=stage_parser] [task=RewardEraSeqCreator] [height=3522026]"}
{"level":"info","time":"2021-02-18T16:57:20.747+0300","msg":"pipeline completed [Err: 1 error occurred:\n\t* record not found\n\n]"}
{"level":"info","time":"2021-02-18T16:58:00.000+0300","msg":"wake, now=2021-02-18T16:58:00+03:00"}
{"level":"info","time":"2021-02-18T16:58:00.000+0300","msg":"running indexer use case [handler=worker] [batchSize=2]"}
{"level":"info","time":"2021-02-18T16:58:00.000+0300","msg":"run, now=2021-02-18T16:58:00+03:00, entry=1, next=2021-02-18T16:58:40+03:00"}
{"level":"info","time":"2021-02-18T16:58:00.019+0300","msg":"starting pipeline [start=3522026] [end=3522027]"}
{"level":"info","time":"2021-02-18T16:58:00.019+0300","msg":"running indexer task [stage=stage_fetcher] [task=Fetcher] [height=3522026]"}
{"level":"info","time":"2021-02-18T16:58:00.710+0300","msg":"running indexer task [stage=stage_fetcher] [task=ValidatorFetcher] [height=3522026]"}
{"level":"info","time":"2021-02-18T16:58:00.710+0300","msg":"running indexer task [stage=stage_syncer] [task=MainSyncer] [height=3522026]"}
{"level":"info","time":"2021-02-18T16:58:00.710+0300","msg":"running indexer task [stage=stage_parser] [task=BlockParser] [height=3522026]"}
{"level":"info","time":"2021-02-18T16:58:00.710+0300","msg":"running indexer task [stage=stage_parser] [task=ValidatorsParser] [height=3522026]"}
{"level":"info","time":"2021-02-18T16:58:00.711+0300","msg":"running indexer task [stage=stage_sequencer] [task=BlockSeqCreator] [height=3522026]"}
{"level":"info","time":"2021-02-18T16:58:00.711+0300","msg":"running indexer task [stage=stage_sequencer] [task=EventSeqCreator] [height=3522026]"}
{"level":"info","time":"2021-02-18T16:58:00.711+0300","msg":"running indexer task [stage=stage_sequencer] [task=ValidatorSessionSeqCreator] [height=3522026]"}
{"level":"info","time":"2021-02-18T16:58:00.711+0300","msg":"running indexer task [stage=stage_sequencer] [task=ValidatorEraSeqCreator] [height=3522026]"}
{"level":"info","time":"2021-02-18T16:58:00.711+0300","msg":"running indexer task [stage=stage_sequencer] [task=TransactionSeqCreator] [height=3522026]"}
{"level":"info","time":"2021-02-18T16:58:00.711+0300","msg":"running indexer task [stage=stage_parser] [task=RewardEraSeqCreator] [height=3522026]"}
{"level":"info","time":"2021-02-18T16:58:00.711+0300","msg":"running indexer task [stage=stage_sequencer] [task=ValidatorSeqCreator] [height=3522026]"}
{"level":"info","time":"2021-02-18T16:58:00.711+0300","msg":"running indexer task [stage=stage_sequencer] [task=AccountEraSeqCreator] [height=3522026]"}
{"level":"info","time":"2021-02-18T16:58:00.712+0300","msg":"running indexer task [stage=stage_parser] [task=RewardEraSeqCreator] [height=3522026]"}
{"level":"info","time":"2021-02-18T16:58:00.713+0300","msg":"running indexer task [stage=stage_parser] [task=RewardEraSeqCreator] [height=3522026]"}
{"level":"info","time":"2021-02-18T16:58:00.714+0300","msg":"pipeline completed [Err: 1 error occurred:\n\t* record not found\n\n]"}
{"level":"info","time":"2021-02-18T16:58:40.000+0300","msg":"wake, now=2021-02-18T16:58:40+03:00"}
{"level":"info","time":"2021-02-18T16:58:40.000+0300","msg":"run, now=2021-02-18T16:58:40+03:00, entry=1, next=2021-02-18T16:59:20+03:00"}
{"level":"info","time":"2021-02-18T16:58:40.000+0300","msg":"running indexer use case [handler=worker] [batchSize=2]"}
{"level":"info","time":"2021-02-18T16:58:40.014+0300","msg":"starting pipeline [start=3522026] [end=3522027]"}
```

Is `record not found` should be considered as errors?

* I've also started an API, but it seems to not return any transactions at all or am I using it wrong?
```
$ curl 127.0.0.1:8081/transactions
{"items":null}
```

* blocks_summary gives me an error as well: ```$ curl 127.0.0.1:8081/blocks_summary
{"error":"Key: 'GetBlockTimesForIntervalRequest.Interval' Error:Field validation for 'Interval' failed on the 'required' tag\nKey: 'GetBlockTimesForIntervalRequest.Period' Error:Field validation for 'Period' failed on the 'required' tag","status":400}``` 

* blocks_summary I've found how to query should be done like this (documentation should be improved):
```
polkadothub@polkadot-indexer:~$ curl "http://127.0.0.1:8081/blocks_summary?interval=hour&period=24"
[{"id":1,"created_at":"2021-02-20T16:01:47.016277+03:00","updated_at":"2021-02-20T16:21:47.017343+03:00","index_version":6,"time_interval":"hour","time_bucket":"2020-12-15T16:00:00+03:00","count":117,"block_time_avg":5.948718}]
polkadothub@polkadot-indexer:~$ curl "http://127.0.0.1:8081/blocks_summary?interval=day&period=24"
[{"id":2,"created_at":"2021-02-20T16:01:47.190677+03:00","updated_at":"2021-02-20T16:21:47.020749+03:00","index_version":6,"time_interval":"day","time_bucket":"2020-12-15T00:00:00+03:00","count":117,"block_time_avg":5.948718}]
```

Mainly I want to extract transactions (extrinsics) for certain accounts and also be able to query transactions by hash, will I be able to do so with this indexer?

Thanks.

@pacmessica @eesmerdag @silentlight

**Comment by gituser** [comment]
I've also tried running indexer starting from `height: 1`, but it gives me this:

```
{"level":"info","time":"2021-02-20T16:52:59.000+0300","msg":"run, now=2021-02-20T16:52:59+03:00, entry=1, next=2021-02-20T16:53:00+03:00"}
{"level":"info","time":"2021-02-20T16:52:59.216+0300","msg":"running indexer task [stage=stage_fetcher] [task=Fetcher] [height=1]"}
{"level":"info","time":"2021-02-20T16:52:59.836+0300","msg":"pipeline completed [Err: rpc error: code = Unavailable desc = could not calculate fee]"}
{"level":"info","time":"2021-02-20T16:53:00.000+0300","msg":"wake, now=2021-02-20T16:53:00+03:00"}
{"level":"info","time":"2021-02-20T16:53:00.000+0300","msg":"run, now=2021-02-20T16:53:00+03:00, entry=1, next=2021-02-20T16:53:01+03:00"}
{"level":"info","time":"2021-02-20T16:53:00.000+0300","msg":"running indexer use case [handler=worker] [batchSize=2]"}
{"level":"info","time":"2021-02-20T16:53:00.011+0300","msg":"starting pipeline [start=1] [end=2]"}
{"level":"info","time":"2021-02-20T16:53:00.011+0300","msg":"running indexer task [stage=stage_fetcher] [task=Fetcher] [height=1]"}
{"level":"info","time":"2021-02-20T16:53:00.643+0300","msg":"running indexer task [stage=stage_fetcher] [task=Fetcher] [height=1]"}
{"level":"info","time":"2021-02-20T16:53:01.000+0300","msg":"wake, now=2021-02-20T16:53:01+03:00"}
{"level":"info","time":"2021-02-20T16:53:01.000+0300","msg":"run, now=2021-02-20T16:53:01+03:00, entry=1, next=2021-02-20T16:53:02+03:00"}
{"level":"info","time":"2021-02-20T16:53:01.000+0300","msg":"skip"}
{"level":"info","time":"2021-02-20T16:53:01.230+0300","msg":"running indexer task [stage=stage_fetcher] [task=Fetcher] [height=1]"}
{"level":"info","time":"2021-02-20T16:53:01.863+0300","msg":"pipeline completed [Err: rpc error: code = Unavailable desc = could not calculate fee]"}
```

**Comment by pacmessica** [comment]
Hey!

So I haven't tried this with Westend but I don't see why it wouldn't work. We've used on polkadot and kusama without any issues.


For the first `record not found` error, I believe you're getting this because you haven't indexed older heights yet (I'm making this assumption). For the reward tasks, they depend on data from an earlier height and if it's not there it'll error. This is because polkadot rewards are created sometime around the beginning of an era, but then need a transaction to claim them which can happen up to 80 eras afterwards. If you're seeing a transaction to claim a reward for an earlier era which you haven't indexed, then you'll get the record not found error. It looks like that is what is happening.

So there's 2 solutions:

1) If you don't care about indexing rewards (which sounds like you don't), then you can run the indexer without the problematic reward task. Just update the `indexer_config.json` versions removing target 12, like this:

```
{
    "versions": [
        {
            "id": 1,
            "targets": [1,2,3,4,5,6,7,8,9,10,11],
            "parallel": false
        }
    ],
```

2) If you want to index rewards, then you need to index all last in era heights first. Use the `last_in_era` flag in `indexer_config.json`, and start the indexer from height 0. It should reindex only last_in_era heights which will be a loooot faster than reindexing all heights from 0.

```
        {
          "targets": [1,2,3,4,5,6,7,8,9,10,11,12],
          "last_in_era": true
        }
```

**Comment by pacmessica** [comment]
We're actually developing a dedicated transaction search worker for polkadot. It'll be very similar to how we run cosmos tx-search, you can check out documentation here to get an idea of the api calls (it'll be slightly different for polkadot). You can see it enables you to search by tx hash an accounts:

https://learn.figment.io/network-documentation/cosmos/enriched-apis/transaction-search
https://github.com/figment-networks/indexer-manager

For this flow, you need to run proxy, a manager, and a worker. The manager code is already publicly available. The polkadot-worker repo itself is actively being developed and will likely be public sometime next week. If you can wait, this sounds like it'll better fits your use case. The transaction data saved in `polkadot-worker` will be more detailed than the data saved in this repo `polkadhub-indexer`.

@gituser let me know if you want to do that, and I can tag you when it's ready :) I didn't answer all your bug questions above because I think polkadot-worker will be better suited for you. However, if you still want me to help you out with running this indexer, let me know

**Comment by gituser** [comment]
Thanks a lot @pacmessica I'll check this out and get back to you.

Sure, please tag me, will be much appreciated!

I have polkadot running in `--archive` mode, and yes I mostly need to search transactions belonging to certain address and not interested that much in rewards.

**Comment by pacmessica** [comment]
@gituser 

Hey [polkadot-worker](https://github.com/figment-networks/polkadot-worker) is now public! Sorry for the wait. We're still testing it out, so may change around a bit. If you have any issues or questions, reach out :) 

We'll also offer polkadot tx-search on [datahub](https://datahub.figment.io) in the future, so there's also the option to use that if you don't want to run your own node.
